[build]
  base = "apps/web"
  command = "npm run build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=../.."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"