[build]
  base = "."
  command = "pnpm install && pnpm --filter web build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Redirect all traffic to Next.js  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200