/*
 * -------------------------------------------------------
 * Add quiz linking functionality to user creation
 * This automatically links quiz responses to users after signup
 * -------------------------------------------------------
 */

-- Function to link quiz responses to a newly created user
create or replace function kit.link_quiz_responses_to_user()
returns trigger 
language plpgsql 
security definer
set search_path = '' as $$
begin
    -- Only process if this is a new user (not an update)
    if TG_OP = 'INSERT' then
        -- Link any unlinked quiz responses with this email to the new user
        update public.quiz_responses 
        set user_id = NEW.id,
            updated_at = now()
        where email = NEW.email 
        and user_id is null;
        
        -- Log the linking for debugging
        if found then
            insert into kit.audit_log (
                event_type,
                user_id,
                details
            ) values (
                'quiz_linked',
                NEW.id,
                jsonb_build_object(
                    'email', NEW.email,
                    'linked_responses', (
                        select count(*) 
                        from public.quiz_responses 
                        where user_id = NEW.id and email = NEW.email
                    )
                )
            );
        end if;
    end if;
    
    return NEW;
end;
$$;

-- Create audit log table if it doesn't exist (for debugging quiz linking)
create table if not exists kit.audit_log (
    id bigint generated by default as identity primary key,
    event_type text not null,
    user_id uuid references auth.users(id),
    details jsonb default '{}'::jsonb,
    created_at timestamp with time zone default now()
);

-- Grant permissions on the audit log table
grant select, insert on kit.audit_log to service_role;

-- Create trigger to link quiz responses after user creation
create trigger link_quiz_responses_after_user_creation
    after insert on auth.users
    for each row
    execute function kit.link_quiz_responses_to_user();

-- Add index for efficient quiz response lookups by email
create index if not exists idx_quiz_responses_email_unlinked 
on public.quiz_responses (email) 
where user_id is null;